#!/usr/bin/env node
// Cross-renderer PARITY matrix, computed from the schema + the ACTUAL renderer
// source so it never drifts. The contract vocabulary comes from the schema (via
// validate.mjs); support is detected by how each renderer registers/dispatches a
// type or action. Run:  node spec/tools/parity.mjs > PARITY.md
//
// This is the measurable definition of the project's core promise — the same
// JSON renders equivalently on iOS, Android and Aurora.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { KNOWN_COMPONENTS, KNOWN_ACTIONS } from './validate.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const read = (rel) => { try { return readFileSync(join(ROOT, rel), 'utf8'); } catch { return ''; } };

const src = {
  iosComp:    read('ios/Sources/SDUIRender/Builtins.swift'),
  andComp:    read('android/sdui/src/main/java/dev/sdui/render/Builtins.kt'),
  auroraComp: read('aurora/qml/sdui/SduiRenderer.qml'),
  iosAct:     read('ios/Sources/SDUIRuntime/ActionInterpreter.swift'),
  andAct:     read('android/sdui/src/main/java/dev/sdui/runtime/ActionInterpreter.kt'),
};

// A component is "supported" where the renderer registers/dispatches its type.
const componentSupport = (t) => ({
  iOS:     src.iosComp.includes(`register("${t}")`),
  Android: src.andComp.includes(`register("${t}")`),
  Aurora:  new RegExp(`case\\s+"${t}"`).test(src.auroraComp),
});
// An action is "supported" where its kind literal appears in the interpreter.
// Aurora has no action runtime yet, so every action is unsupported there.
const actionSupport = (a) => ({
  iOS:     new RegExp(`"${a}"`).test(src.iosAct),
  Android: new RegExp(`"${a}"`).test(src.andAct),
  Aurora:  false,
});

const mark = (b) => (b ? '✅' : '—');
const PLATFORMS = ['iOS', 'Android', 'Aurora'];

function table(title, items, supportOf) {
  const rows = items.map((name) => {
    const s = supportOf(name);
    return `| \`${name}\` | ${PLATFORMS.map((p) => mark(s[p])).join(' | ')} |`;
  });
  const totals = PLATFORMS.map((p) => items.filter((n) => supportOf(n)[p]).length);
  const out = [];
  out.push(`### ${title} (${items.length})`, '');
  out.push(`| ${title.slice(0, -1) || title} | ${PLATFORMS.join(' | ')} |`);
  out.push(`|${'---|'.repeat(PLATFORMS.length + 1)}`);
  out.push(...rows);
  out.push(`| **supported** | ${totals.map((t, i) => `**${t}/${items.length}**`).join(' | ')} |`);
  out.push('');
  return out.join('\n');
}

function gaps(label, items, supportOf) {
  const out = [`### Gaps — ${label}`, ''];
  for (const p of PLATFORMS) {
    const missing = items.filter((n) => !supportOf(n)[p]);
    out.push(`- **${p}** missing ${missing.length}: ${missing.length ? missing.map((m) => `\`${m}\``).join(', ') : '_none — full parity_'}`);
  }
  out.push('');
  return out.join('\n');
}

const components = [...KNOWN_COMPONENTS].sort();
const actions = [...KNOWN_ACTIONS].sort();

const doc = [
  '# Renderer parity matrix',
  '',
  '> Generated by `node spec/tools/parity.mjs` from the schema + the actual renderer',
  '> source. Do not edit by hand — re-run after changing any renderer. This is the',
  '> measurable definition of "one contract, three equal renderers".',
  '',
  '`✅` = supported · `—` = not yet implemented (degrades safely, never crashes).',
  '',
  '## Components',
  '',
  table('Components', components, componentSupport),
  gaps('components', components, componentSupport),
  '## Actions',
  '',
  table('Actions', actions, actionSupport),
  gaps('actions', actions, actionSupport),
  '_Aurora has no action runtime yet — porting it is the top Aurora parity task._',
  '',
].join('\n');

process.stdout.write(doc + '\n');
